 -- DDL for the expense report schema

CREATE DATABASE EXPENSES ;

CREATE ROLE EXPENSES WITH PASSWORD 'EXPENSES' ;

GRANT ALL PRIVILEGES ON DATABASE EXPENSES TO EXPENSES ;

CREATE TABLE public.ACCOUNT_HOLDER (
                ACCOUNT_HOLDER_ID BIGINT NOT NULL,
                AUTHORIZING_ACCOUNT_HOLDER_ID BIGINT NOT NULL,
                FIRST_NAME VARCHAR(255) NOT NULL,
                LAST_NAME VARCHAR(255) NOT NULL,
                EMAIL VARCHAR(255) NOT NULL,
                CONSTRAINT account_holder_id PRIMARY KEY (ACCOUNT_HOLDER_ID)
);


CREATE UNIQUE INDEX primary_key_3
 ON public.ACCOUNT_HOLDER
 ( ACCOUNT_HOLDER_ID ASC );

CREATE INDEX constraint_3_index_3
 ON public.ACCOUNT_HOLDER
 ( AUTHORIZING_ACCOUNT_HOLDER_ID ASC );

CREATE TABLE public.CHARGE_BATCH (
                CHARGE_BATCH_ID BIGINT NOT NULL,
                IMPORT_TIME TIMESTAMP NOT NULL,
                ACCOUNT_HOLDER_ID BIGINT NOT NULL,
                CONSTRAINT charge_batch_id PRIMARY KEY (CHARGE_BATCH_ID)
);
COMMENT ON TABLE public.CHARGE_BATCH IS 'the batch of new charges as imported from a credit card source. this is simply the unit to describe imported charges.';


CREATE TABLE public.CHARGE (
                CHARGE_ID BIGINT NOT NULL,
                CHARGE_BATCH_ID BIGINT NOT NULL,
                CHARGE_AMOUNT DOUBLE PRECISION NOT NULL,
                DESCRIPTION VARCHAR(1000) NOT NULL,
                CONSTRAINT charge_id PRIMARY KEY (CHARGE_ID)
);


CREATE TABLE public.CREDIT_CARD (
                CREDIT_CARD_ID BIGINT NOT NULL,
                ACCOUNT_HOLDER_ID BIGINT NOT NULL,
                CONSTRAINT credit_card_id PRIMARY KEY (CREDIT_CARD_ID)
);


ALTER TABLE public.ACCOUNT_HOLDER ADD CONSTRAINT constraint_3
FOREIGN KEY (AUTHORIZING_ACCOUNT_HOLDER_ID)
REFERENCES public.ACCOUNT_HOLDER (ACCOUNT_HOLDER_ID)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE public.CREDIT_CARD ADD CONSTRAINT credit_card_account_holder_fk
FOREIGN KEY (ACCOUNT_HOLDER_ID)
REFERENCES public.ACCOUNT_HOLDER (ACCOUNT_HOLDER_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.CHARGE_BATCH ADD CONSTRAINT charge_batch_account_holder_fk
FOREIGN KEY (ACCOUNT_HOLDER_ID)
REFERENCES public.ACCOUNT_HOLDER (ACCOUNT_HOLDER_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.CHARGE ADD CONSTRAINT charge_charge_batch_fk
FOREIGN KEY (CHARGE_BATCH_ID)
REFERENCES public.CHARGE_BATCH (CHARGE_BATCH_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;