package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 12:43:19 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;

/**
 * Charge generated by hbm2java
 */
@Entity
@Table(name = "charge"
		      , schema = "public"
)
public class Charge implements java.io.Serializable {


	private long chargeId;
	private ChargeBatch chargeBatch;
	private double chargeAmount;
	private String description;

	public Charge() {
	}

	public Charge(long chargeId, ChargeBatch chargeBatch, double chargeAmount, String description) {
		this.chargeId = chargeId;
		this.chargeBatch = chargeBatch;
		this.chargeAmount = chargeAmount;
		this.description = description;
	}

	@Id

	@Column(name = "charge_id", unique = true, nullable = false)
	public long getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(long chargeId) {
		this.chargeId = chargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "charge_batch_id", nullable = false)
	public ChargeBatch getChargeBatch() {
		return this.chargeBatch;
	}

	public void setChargeBatch(ChargeBatch chargeBatch) {
		this.chargeBatch = chargeBatch;
	}

	@Column(name = "charge_amount", nullable = false, precision = 17, scale = 17)
	public double getChargeAmount() {
		return this.chargeAmount;
	}

	public void setChargeAmount(double chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}


