package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 1:50:40 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ChargeBatch generated by hbm2java
 */
@Entity
@Table(name = "charge_batch"
		      , schema = "public"
)
public class ChargeBatch implements java.io.Serializable {


	private long chargeBatchId;
	private ExpenseHolder expenseHolder;
	private Date importTime;
	private Set<Charge> charges = new HashSet<Charge>(0);

	public ChargeBatch() {
	}


	public ChargeBatch(long chargeBatchId, ExpenseHolder expenseHolder, Date importTime) {
		this.chargeBatchId = chargeBatchId;
		this.expenseHolder = expenseHolder;
		this.importTime = importTime;
	}

	public ChargeBatch(long chargeBatchId, ExpenseHolder expenseHolder, Date importTime, Set<Charge> charges) {
		this.chargeBatchId = chargeBatchId;
		this.expenseHolder = expenseHolder;
		this.importTime = importTime;
		this.charges = charges;
	}

	@Id

	@Column(name = "charge_batch_id", unique = true, nullable = false)
	public long getChargeBatchId() {
		return this.chargeBatchId;
	}

	public void setChargeBatchId(long chargeBatchId) {
		this.chargeBatchId = chargeBatchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expense_holder_id", nullable = false)
	public ExpenseHolder getExpenseHolder() {
		return this.expenseHolder;
	}

	public void setExpenseHolder(ExpenseHolder expenseHolder) {
		this.expenseHolder = expenseHolder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_time", nullable = false, length = 29)
	public Date getImportTime() {
		return this.importTime;
	}

	public void setImportTime(Date importTime) {
		this.importTime = importTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "chargeBatch")
	public Set<Charge> getCharges() {
		return this.charges;
	}

	public void setCharges(Set<Charge> charges) {
		this.charges = charges;
	}


}


