package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 12:43:19 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;

/**
 * CreditCard generated by hbm2java
 */
@Entity
@Table(name = "credit_card"
		      , schema = "public"
)
public class CreditCard implements java.io.Serializable {


	private long creditCardId;
	private AccountHolder accountHolder;

	public CreditCard() {
	}

	public CreditCard(long creditCardId, AccountHolder accountHolder) {
		this.creditCardId = creditCardId;
		this.accountHolder = accountHolder;
	}

	@Id

	@Column(name = "credit_card_id", unique = true, nullable = false)
	public long getCreditCardId() {
		return this.creditCardId;
	}

	public void setCreditCardId(long creditCardId) {
		this.creditCardId = creditCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_holder_id", nullable = false)
	public AccountHolder getAccountHolder() {
		return this.accountHolder;
	}

	public void setAccountHolder(AccountHolder accountHolder) {
		this.accountHolder = accountHolder;
	}


}


