package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 1:50:40 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpenseReportLine generated by hbm2java
 */
@Entity
@Table(name = "expense_report_line"
		      , schema = "public"
)
public class ExpenseReportLine implements java.io.Serializable {


	private long expenseReportLineId;
	private Charge charge;
	private ExpenseReport expenseReport;
	private boolean personalExpense;
	private String justification;
	private Set<Attachment> attachments = new HashSet<Attachment>(0);

	public ExpenseReportLine() {
	}


	public ExpenseReportLine(long expenseReportLineId, Charge charge, ExpenseReport expenseReport, boolean personalExpense, String justification) {
		this.expenseReportLineId = expenseReportLineId;
		this.charge = charge;
		this.expenseReport = expenseReport;
		this.personalExpense = personalExpense;
		this.justification = justification;
	}

	public ExpenseReportLine(long expenseReportLineId, Charge charge, ExpenseReport expenseReport, boolean personalExpense, String justification, Set<Attachment> attachments) {
		this.expenseReportLineId = expenseReportLineId;
		this.charge = charge;
		this.expenseReport = expenseReport;
		this.personalExpense = personalExpense;
		this.justification = justification;
		this.attachments = attachments;
	}

	@Id

	@Column(name = "expense_report_line_id", unique = true, nullable = false)
	public long getExpenseReportLineId() {
		return this.expenseReportLineId;
	}

	public void setExpenseReportLineId(long expenseReportLineId) {
		this.expenseReportLineId = expenseReportLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "charge_id", nullable = false)
	public Charge getCharge() {
		return this.charge;
	}

	public void setCharge(Charge charge) {
		this.charge = charge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expense_report_id", nullable = false)
	public ExpenseReport getExpenseReport() {
		return this.expenseReport;
	}

	public void setExpenseReport(ExpenseReport expenseReport) {
		this.expenseReport = expenseReport;
	}

	@Column(name = "personal_expense", nullable = false)
	public boolean isPersonalExpense() {
		return this.personalExpense;
	}

	public void setPersonalExpense(boolean personalExpense) {
		this.personalExpense = personalExpense;
	}

	@Column(name = "justification", nullable = false, length = 1000)
	public String getJustification() {
		return this.justification;
	}

	public void setJustification(String justification) {
		this.justification = justification;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "expenseReportLine")
	public Set<Attachment> getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Set<Attachment> attachments) {
		this.attachments = attachments;
	}


}


