package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 1:50:40 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpenseReport generated by hbm2java
 */
@Entity
@Table(name = "expense_report"
		      , schema = "public"
)
public class ExpenseReport implements java.io.Serializable {


	private long expenseReportId;
	private ExpenseHolder expenseHolder;
	private Set<ExpenseReportLine> expenseReportLines = new HashSet<ExpenseReportLine>(0);

	public ExpenseReport() {
	}


	public ExpenseReport(long expenseReportId, ExpenseHolder expenseHolder) {
		this.expenseReportId = expenseReportId;
		this.expenseHolder = expenseHolder;
	}

	public ExpenseReport(long expenseReportId, ExpenseHolder expenseHolder, Set<ExpenseReportLine> expenseReportLines) {
		this.expenseReportId = expenseReportId;
		this.expenseHolder = expenseHolder;
		this.expenseReportLines = expenseReportLines;
	}

	@Id

	@Column(name = "expense_report_id", unique = true, nullable = false)
	public long getExpenseReportId() {
		return this.expenseReportId;
	}

	public void setExpenseReportId(long expenseReportId) {
		this.expenseReportId = expenseReportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expense_holder_id", nullable = false)
	public ExpenseHolder getExpenseHolder() {
		return this.expenseHolder;
	}

	public void setExpenseHolder(ExpenseHolder expenseHolder) {
		this.expenseHolder = expenseHolder;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "expenseReport")
	public Set<ExpenseReportLine> getExpenseReportLines() {
		return this.expenseReportLines;
	}

	public void setExpenseReportLines(Set<ExpenseReportLine> expenseReportLines) {
		this.expenseReportLines = expenseReportLines;
	}


}


