package org.springsource.examples.expenses.model;

import javax.persistence.*;
import java.util.Date;

/**
 * ExpenseReportAuthorization generated by hbm2java
 */
@Entity
@EntityListeners(org.springsource.examples.expenses.services.util.AuditingJpaEntityFieldListener.class)
@Table(name = "expense_report_authorization", schema = "public")
public class ExpenseReportAuthorization implements java.io.Serializable {
	private long expenseReportAuthorizationId;
	private ExpenseReport expenseReport;
	private Date approvalTime;
	private boolean approved;
	private boolean rejected;
	private Date rejectedTime;
	private long authorizingExpenseHolderId;
	private String descriptionOfResponse;

	public ExpenseReportAuthorization() {
	}

	public ExpenseReportAuthorization(long expenseReportAuthorizationId, ExpenseReport expenseReport, Date approvalTime, boolean approved, boolean rejected, Date rejectedTime, long authorizingExpenseHolderId, String descriptionOfResponse) {
		this.expenseReportAuthorizationId = expenseReportAuthorizationId;
		this.expenseReport = expenseReport;
		this.approvalTime = approvalTime;
		this.approved = approved;
		this.rejected = rejected;
		this.rejectedTime = rejectedTime;
		this.authorizingExpenseHolderId = authorizingExpenseHolderId;
		this.descriptionOfResponse = descriptionOfResponse;
	}

	private java.util.Date dateCreated;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dc) {
		this.dateCreated = dc;
	}


	private java.util.Date dateModified;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 10)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dc) {
		this.dateModified = dc;
	}


	private java.lang.Long version;

	@javax.persistence.Version
	public java.lang.Long getVersion() {
		return version;
	}

	public void setVersion(java.lang.Long value) {
		this.version = value;
	}

	@Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
	@Column(name = "expense_report_authorization_id", unique = true, nullable = false)
	public long getExpenseReportAuthorizationId() {
		return this.expenseReportAuthorizationId;
	}

	public void setExpenseReportAuthorizationId(long expenseReportAuthorizationId) {
		this.expenseReportAuthorizationId = expenseReportAuthorizationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expense_report_id", nullable = false)
	public ExpenseReport getExpenseReport() {
		return this.expenseReport;
	}

	public void setExpenseReport(ExpenseReport expenseReport) {
		this.expenseReport = expenseReport;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approval_time", nullable = false, length = 29)
	public Date getApprovalTime() {
		return this.approvalTime;
	}

	public void setApprovalTime(Date approvalTime) {
		this.approvalTime = approvalTime;
	}

	@Column(name = "approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	@Column(name = "rejected", nullable = false)
	public boolean isRejected() {
		return this.rejected;
	}

	public void setRejected(boolean rejected) {
		this.rejected = rejected;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rejected_time", nullable = false, length = 29)
	public Date getRejectedTime() {
		return this.rejectedTime;
	}

	public void setRejectedTime(Date rejectedTime) {
		this.rejectedTime = rejectedTime;
	}

	@Column(name = "authorizing_expense_holder_id", nullable = false)
	public long getAuthorizingExpenseHolderId() {
		return this.authorizingExpenseHolderId;
	}

	public void setAuthorizingExpenseHolderId(long authorizingExpenseHolderId) {
		this.authorizingExpenseHolderId = authorizingExpenseHolderId;
	}

	@Column(name = "description_of_response", nullable = false, length = 1000)
	public String getDescriptionOfResponse() {
		return this.descriptionOfResponse;
	}

	public void setDescriptionOfResponse(String descriptionOfResponse) {
		this.descriptionOfResponse = descriptionOfResponse;
	}
}