package org.springsource.examples.expenses.model;
// Generated Aug 5, 2011 1:50:40 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpenseHolder generated by hbm2java
 */
@Entity
@Table(name = "expense_holder"
		      , schema = "public"
)
public class ExpenseHolder implements java.io.Serializable {


	private long expenseHolderId;
	private ExpenseHolder authorizingExpenseHolder;
	private String firstName;
	private String lastName;
	private String email;
	private Set<ExpenseReport> expenseReports = new HashSet<ExpenseReport>(0);
	private Set<CreditCard> creditCards = new HashSet<CreditCard>(0);
	private Set<ChargeBatch> chargeBatchs = new HashSet<ChargeBatch>(0);
	private Set<ExpenseHolder> expenseHolders = new HashSet<ExpenseHolder>(0);

	public ExpenseHolder() {
	}


	public ExpenseHolder(long expenseHolderId, ExpenseHolder authorizingExpenseHolder, String firstName, String lastName, String email) {
		this.expenseHolderId = expenseHolderId;
		this.authorizingExpenseHolder = authorizingExpenseHolder;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	public ExpenseHolder(long expenseHolderId, ExpenseHolder authorizingExpenseHolder, String firstName, String lastName, String email, Set<ExpenseReport> expenseReports, Set<CreditCard> creditCards, Set<ChargeBatch> chargeBatchs, Set<ExpenseHolder> expenseHolders) {
		this.expenseHolderId = expenseHolderId;
		this.authorizingExpenseHolder = authorizingExpenseHolder;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.expenseReports = expenseReports;
		this.creditCards = creditCards;
		this.chargeBatchs = chargeBatchs;
		this.expenseHolders = expenseHolders;
	}

	@Id

	@Column(name = "expense_holder_id", unique = true, nullable = false)
	public long getExpenseHolderId() {
		return this.expenseHolderId;
	}

	public void setExpenseHolderId(long expenseHolderId) {
		this.expenseHolderId = expenseHolderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authorizing_expense_holder_id", nullable = false)
	public ExpenseHolder getAuthorizingExpenseHolder() {
		return this.authorizingExpenseHolder;
	}

	public void setAuthorizingExpenseHolder(ExpenseHolder authorizingExpenseHolder) {
		this.authorizingExpenseHolder = authorizingExpenseHolder;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "expenseHolder")
	public Set<ExpenseReport> getExpenseReports() {
		return this.expenseReports;
	}

	public void setExpenseReports(Set<ExpenseReport> expenseReports) {
		this.expenseReports = expenseReports;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "expenseHolder")
	public Set<CreditCard> getCreditCards() {
		return this.creditCards;
	}

	public void setCreditCards(Set<CreditCard> creditCards) {
		this.creditCards = creditCards;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "expenseHolder")
	public Set<ChargeBatch> getChargeBatchs() {
		return this.chargeBatchs;
	}

	public void setChargeBatchs(Set<ChargeBatch> chargeBatchs) {
		this.chargeBatchs = chargeBatchs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "authorizingExpenseHolder")
	public Set<ExpenseHolder> getExpenseHolders() {
		return this.expenseHolders;
	}

	public void setExpenseHolders(Set<ExpenseHolder> expenseHolders) {
		this.expenseHolders = expenseHolders;
	}


}


