create database expenses ;
create role expenses with password 'expenses' ;
grant all privileges on database expenses to expenses ;



CREATE TABLE public.MANAGED_FILE (
                MANAGED_FILE_ID BIGINT NOT NULL,
                EXTENSION VARCHAR(10) NOT NULL,
                BYTE_SIZE DOUBLE PRECISION NOT NULL,
                ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
                READY BOOLEAN NOT NULL,
                MOUNT_PREFIX VARCHAR(10) NOT NULL,
                PRIORITY INTEGER NOT NULL,
                CONSTRAINT managed_file_id PRIMARY KEY (MANAGED_FILE_ID)
);


CREATE TABLE public.EXPENSE_HOLDER (
                EXPENSE_HOLDER_ID BIGINT NOT NULL,
                AUTHORIZING_EXPENSE_HOLDER_ID BIGINT NOT NULL,
                FIRST_NAME VARCHAR(255) NOT NULL,
                LAST_NAME VARCHAR(255) NOT NULL,
                EMAIL VARCHAR(255) NOT NULL,
                CONSTRAINT expense_holder_id PRIMARY KEY (EXPENSE_HOLDER_ID)
);


CREATE UNIQUE INDEX primary_key_3
 ON public.EXPENSE_HOLDER
 ( EXPENSE_HOLDER_ID ASC );

CREATE INDEX constraint_3_index_3
 ON public.EXPENSE_HOLDER
 ( AUTHORIZING_EXPENSE_HOLDER_ID ASC );

CREATE TABLE public.EXPENSE_REPORT (
                EXPENSE_REPORT_ID BIGINT NOT NULL,
                EXPENSE_HOLDER_ID BIGINT NOT NULL,
                CONSTRAINT expense_report_id PRIMARY KEY (EXPENSE_REPORT_ID)
);


CREATE TABLE public.CHARGE_BATCH (
                CHARGE_BATCH_ID BIGINT NOT NULL,
                IMPORT_TIME TIMESTAMP NOT NULL,
                EXPENSE_HOLDER_ID BIGINT NOT NULL,
                CONSTRAINT charge_batch_id PRIMARY KEY (CHARGE_BATCH_ID)
);
COMMENT ON TABLE public.CHARGE_BATCH IS 'the batch of new charges as imported from a credit card source. this is simply the unit to describe imported charges.';


CREATE TABLE public.CHARGE (
                CHARGE_ID BIGINT NOT NULL,
                CHARGE_BATCH_ID BIGINT NOT NULL,
                CHARGE_AMOUNT DOUBLE PRECISION NOT NULL,
                DESCRIPTION VARCHAR(1000) NOT NULL,
                CONSTRAINT charge_id PRIMARY KEY (CHARGE_ID)
);
COMMENT ON TABLE public.CHARGE IS 'a single charge, as imported from a credit card source. It belongs to a charge_batch, but it will be accounted for in an expense_report.';


CREATE TABLE public.EXPENSE_REPORT_LINE (
                EXPENSE_REPORT_LINE_ID BIGINT NOT NULL,
                PERSONAL_EXPENSE BOOLEAN NOT NULL,
                JUSTIFICATION VARCHAR(1000) NOT NULL,
                EXPENSE_REPORT_ID BIGINT NOT NULL,
                CHARGE_ID BIGINT NOT NULL,
                CONSTRAINT expense_report_line_id PRIMARY KEY (EXPENSE_REPORT_LINE_ID)
);
COMMENT ON TABLE public.EXPENSE_REPORT_LINE IS 'Represents individual lines on an expense report. Ties together uploaded attachments (e.g., scanned-in, or photographed, receipts ) and individual charges.';


CREATE TABLE public.ATTACHMENT (
                ATTACHMENT_ID BIGINT NOT NULL,
                EXPENSE_REPORT_LINE_ID BIGINT NOT NULL,
                MANAGED_FILE_ID BIGINT NOT NULL,
                CONSTRAINT attachment_id PRIMARY KEY (ATTACHMENT_ID)
);


CREATE TABLE public.CREDIT_CARD (
                CREDIT_CARD_ID BIGINT NOT NULL,
                EXPENSE_HOLDER_ID BIGINT NOT NULL,
                CONSTRAINT credit_card_id PRIMARY KEY (CREDIT_CARD_ID)
);


ALTER TABLE public.ATTACHMENT ADD CONSTRAINT managed_file_attachment_fk
FOREIGN KEY (MANAGED_FILE_ID)
REFERENCES public.MANAGED_FILE (MANAGED_FILE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.EXPENSE_HOLDER ADD CONSTRAINT constraint_3
FOREIGN KEY (AUTHORIZING_EXPENSE_HOLDER_ID)
REFERENCES public.EXPENSE_HOLDER (EXPENSE_HOLDER_ID)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE public.CREDIT_CARD ADD CONSTRAINT credit_card_account_holder_fk
FOREIGN KEY (EXPENSE_HOLDER_ID)
REFERENCES public.EXPENSE_HOLDER (EXPENSE_HOLDER_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.CHARGE_BATCH ADD CONSTRAINT charge_batch_account_holder_fk
FOREIGN KEY (EXPENSE_HOLDER_ID)
REFERENCES public.EXPENSE_HOLDER (EXPENSE_HOLDER_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.EXPENSE_REPORT ADD CONSTRAINT account_holder_expense_report_fk
FOREIGN KEY (EXPENSE_HOLDER_ID)
REFERENCES public.EXPENSE_HOLDER (EXPENSE_HOLDER_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.EXPENSE_REPORT_LINE ADD CONSTRAINT expense_report_expense_report_line_fk
FOREIGN KEY (EXPENSE_REPORT_ID)
REFERENCES public.EXPENSE_REPORT (EXPENSE_REPORT_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.CHARGE ADD CONSTRAINT charge_charge_batch_fk
FOREIGN KEY (CHARGE_BATCH_ID)
REFERENCES public.CHARGE_BATCH (CHARGE_BATCH_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.EXPENSE_REPORT_LINE ADD CONSTRAINT charge_expense_report_line_fk
FOREIGN KEY (CHARGE_ID)
REFERENCES public.CHARGE (CHARGE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.ATTACHMENT ADD CONSTRAINT attachment_expense_report_line_fk
FOREIGN KEY (EXPENSE_REPORT_LINE_ID)
REFERENCES public.EXPENSE_REPORT_LINE (EXPENSE_REPORT_LINE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;